# Server
server.port=8080

# Database (MySQL) - LOCALHOST FOR LOCAL DEV
spring.datasource.url=jdbc:mysql://localhost:3306/travelapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=cc96dc9244d7f1d59d212e83de63ca984c7d7d010cbad5eaf803c2bceca8db59
jwt.expiration=86400000

# File uploads
upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mail (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hamza.mbarki@esprit.tn
spring.mail.password=nzkqyhdnazfgiwpu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=false

# Logging (optional)
logging.level.root=INFO
logging.level.com.example.travelapp=DEBUG